### ISSUE TITLE
compilation terminated.

### ISSUE THREAD

**Issue by cuge1995** [HarborZeng/pointnet2-keras#1]
./tf_grouping_compile.sh: line 3: nvcc: command not found
tf_grouping.cpp:6:10: fatal error: tensorflow/core/framework/op.h: No such file or directory
 #include "tensorflow/core/framework/op.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

这是为啥呢？

**Comment by HarborZeng** [comment]
你的电脑没有安装 cuda 吧，或者没有安装成功？
